name: AutoCoder
on:
  issues:
    types:
      - labeled

env:
  SCRIPT_PATH: ./scripts/script.sh

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    if: contains(github.event.issue.labels.*.name, 'autocoder-bot')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure Git
        run: | 
          git config --local user.name 'autocoder-bot'
          git config --local user.email 'actions@github.com'

      - name: AutoCoder Composite Action
        uses: iammuhit/hyper-autocoder@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          issue_label: 'autocoder-bot'
