name: AutoCoder

on:
  issues:
    types: [opened, reopened, labeled]

env:
  SCRIPT_PATH: ./scripts/script.sh

jobs:
  build:
    if: contains(github.event.issue.labels.*.name, 'autocoder-bot')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Make Script Executable
        run: chmod +x ./scripts/script.sh

      - name: Generate Code with ChatGPT
        id: generate_code
        env:
          GITHUB_TOKEN: ${{ github.token }}
          REPOSITORY: ${{ github.repository }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: ./scripts/script.sh $GITHUB_TOKEN $REPOSITORY $ISSUE_NUMBER $OPENAI_API_KEY

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: autocoder-artifact
          path: autocoder-bot/

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: autocoder-artifact
          path: autocoder-artifact/

      - name: Display Generated Code using the ls command
        run: ls -R autocoder-artifact/
