name: AutoCoder
on:
  issues:
    types: ["opened", "reopened", "labeled"]

env:
  SCRIPT_PATH: ./scripts/script.sh

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    if: contains(github.event.issue.labels.*.name, 'autocoder-bot')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: AutoCoder Composite Action
        uses: iammuhit/hyper-autocoder@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LABEL: 'autocoder-bot'
